import { useState, useEffect } from "react";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { useAnalysis } from "../context/AnalysisContext";
import { Copy, Download, Check, Send, Sparkles } from "lucide-react";

const PRGenerator = () => {
  const { requirementId, reviewResult, reviewData } = useAnalysis();
  const [copied, setCopied] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const defaultTitle = reviewData?.prDraft?.title || `[${requirementId || "JIRA-241"}] AI Impact & Pre-Review: Multi-Factor Authentication & Order Rate Limit`;

  const defaultDescription = reviewResult
    ? `## Automated AI Pre-Review Summary (${requirementId})

${reviewResult}

---
*Generated by ImpactIQ AI Multi-Agent Platform*`
    : `## Summary
• Implemented 2FA TOTP verification on checkout for high-value orders (> $500).
• Enforced 40% maximum discount threshold in discountService.
• Updated Order schema to store \`requires2FA\` boolean status.
• Added test coverage in \`tests/checkout.test.js\`.

## Linked Requirement
${requirementId || "JIRA-241"}

## Files Touched
• src/controllers/checkoutController.js
• src/services/discountService.js
• src/models/Order.js
• tests/checkout.test.js

## Pre-Review Checklist
✔ Unit tests updated
✔ Code quality & linting passed
✔ Backward compatibility preserved`;

  const [prTitle, setPrTitle] = useState(defaultTitle);
  const [prBody, setPrBody] = useState(defaultDescription);

  useEffect(() => {
    if (reviewData?.prDraft?.title) {
      setPrTitle(reviewData.prDraft.title);
    }
    if (reviewResult) {
      setPrBody(`## Automated AI Pre-Review Summary (${requirementId})\n\n${reviewResult}\n\n---\n*Generated by ImpactIQ AI Multi-Agent Platform*`);
    }
  }, [reviewResult, reviewData, requirementId]);

  const handleCopy = () => {
    navigator.clipboard.writeText(`${prTitle}\n\n${prBody}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleExport = () => {
    const blob = new Blob([`${prTitle}\n\n${prBody}`], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `PULL_REQUEST_${requirementId || "DRAFT"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleSubmit = () => {
    setSubmitted(true);
    setTimeout(() => setSubmitted(false), 3000);
  };

  return (
    <>
      <Navbar />

      <div
        style={{
          display: "flex",
          background: "#0B1220",
          minHeight: "calc(100vh - 72px)",
        }}
      >
        <Sidebar />

        <div
          style={{
            flex: 1,
            padding: "30px",
          }}
        >
          <h1 style={{ fontSize: "28px", margin: 0 }}>AI Pull Request Generator</h1>
          <p
            style={{
              color: "#9CA3AF",
              marginTop: "6px",
              marginBottom: "30px",
            }}
          >
            AI automatically synthesizes the requirement scope, touched files, and code review into a ready-to-merge Pull Request.
          </p>

          {/* PR Title */}
          <div className="card" style={{ padding: "25px", marginBottom: "20px" }}>
            <h2 style={{ fontSize: "16px", marginBottom: "10px", color: "#D1D5DB" }}>PR Title</h2>
            <input
              type="text"
              value={prTitle}
              onChange={(e) => setPrTitle(e.target.value)}
              style={{
                width: "100%",
                padding: "14px 16px",
                background: "#1F2937",
                border: "1px solid rgba(255,255,255,0.1)",
                color: "white",
                borderRadius: "10px",
                fontSize: "14px",
                boxSizing: "border-box",
              }}
            />
          </div>

          {/* Description */}
          <div className="card" style={{ padding: "25px", marginBottom: "20px" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "10px" }}>
              <h2 style={{ fontSize: "16px", color: "#D1D5DB", margin: 0 }}>PR Description (Markdown)</h2>
              {reviewResult && (
                <span style={{ fontSize: "12px", color: "#818CF8", display: "flex", alignItems: "center", gap: "4px" }}>
                  <Sparkles size={14} /> Synthesized from Gemini AI Pre-Review
                </span>
              )}
            </div>

            <textarea
              rows={12}
              value={prBody}
              onChange={(e) => setPrBody(e.target.value)}
              style={{
                width: "100%",
                padding: "18px",
                background: "#1F2937",
                color: "white",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: "10px",
                fontSize: "14px",
                lineHeight: "1.6",
                resize: "vertical",
                fontFamily: "inherit",
                boxSizing: "border-box",
              }}
            />
          </div>

          {/* Actions */}
          <div style={{ display: "flex", gap: "15px", alignItems: "center" }}>
            <button
              onClick={handleCopy}
              className="primary-btn"
              style={{ display: "flex", alignItems: "center", gap: "8px" }}
            >
              {copied ? <Check size={18} color="#22C55E" /> : <Copy size={18} />}
              {copied ? "Copied to Clipboard!" : "Copy PR"}
            </button>

            <button
              onClick={handleExport}
              className="primary-btn"
              style={{
                background: "#1F2937",
                border: "1px solid rgba(255,255,255,0.1)",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              <Download size={18} /> Export Markdown
            </button>

            <button
              onClick={handleSubmit}
              className="primary-btn"
              style={{
                background: "#059669",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              }}
            >
              {submitted ? <Check size={18} /> : <Send size={18} />}
              {submitted ? "Submitted to GitHub!" : "Submit for Review"}
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default PRGenerator;